# Generated by Django 5.0.14 on 2026-05-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="target_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="receipt_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="payments/receipts/"
            ),
        ),
    ]
