version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py create_roles && python manage.py seed_db && daphne -b 0.0.0.0 -p 8000 dastdoosti.asgi:application"
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=dastdoosti.settings
    restart: unless-stopped
