# Generated by Django 5.0.14 on 2026-06-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_card_number",
                    models.CharField(
                        default="1234-5678-9012-3456",
                        max_length=20,
                        verbose_name="شماره کارت بانکی",
                    ),
                ),
                (
                    "telegram_bot_token",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="توکن ربات تلگرام",
                    ),
                ),
                (
                    "chat_reply_rule",
                    models.CharField(
                        choices=[
                            ("premium_only", "فقط ویژه (جفت کاربران باید ویژه باشند)"),
                            (
                                "sender_premium",
                                "فرستنده ویژه کافیست (اگر فرستنده ویژه باشد گیرنده هم می\u200cتواند جواب دهد)",
                            ),
                        ],
                        default="sender_premium",
                        max_length=20,
                        verbose_name="قانون جواب دادن به چت",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
    ]
