# Generated by Django 5.0.14 on 2026-06-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_rate",
                    models.FloatField(default=0.05, verbose_name="نرخ کمیسیون"),
                ),
                (
                    "min_claim_threshold",
                    models.IntegerField(default=100, verbose_name="حداقل میزان برداشت"),
                ),
            ],
            options={
                "verbose_name": "تنظیمات رشد",
                "verbose_name_plural": "تنظیمات رشد",
            },
        ),
    ]
