# Generated by Django 5.0.14 on 2026-05-31 05:20

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="birth_date",
        ),
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (18, "18 سال"),
                    (19, "19 سال"),
                    (20, "20 سال"),
                    (21, "21 سال"),
                    (22, "22 سال"),
                    (23, "23 سال"),
                    (24, "24 سال"),
                    (25, "25 سال"),
                    (26, "26 سال"),
                    (27, "27 سال"),
                    (28, "28 سال"),
                    (29, "29 سال"),
                    (30, "30 سال"),
                    (31, "31 سال"),
                    (32, "32 سال"),
                    (33, "33 سال"),
                    (34, "34 سال"),
                    (35, "35 سال"),
                    (36, "36 سال"),
                    (37, "37 سال"),
                    (38, "38 سال"),
                    (39, "39 سال"),
                    (40, "40 سال"),
                    (41, "41 سال"),
                    (42, "42 سال"),
                    (43, "43 سال"),
                    (44, "44 سال"),
                    (45, "45 سال"),
                    (46, "46 سال"),
                    (47, "47 سال"),
                    (48, "48 سال"),
                    (49, "49 سال"),
                    (50, "50 سال"),
                    (51, "51 سال"),
                    (52, "52 سال"),
                    (53, "53 سال"),
                    (54, "54 سال"),
                    (55, "55 سال"),
                    (56, "56 سال"),
                    (57, "57 سال"),
                    (58, "58 سال"),
                    (59, "59 سال"),
                    (60, "60 سال"),
                    (61, "61 سال"),
                    (62, "62 سال"),
                    (63, "63 سال"),
                    (64, "64 سال"),
                    (65, "65 سال"),
                    (66, "66 سال"),
                    (67, "67 سال"),
                    (68, "68 سال"),
                    (69, "69 سال"),
                    (70, "70 سال"),
                    (71, "71 سال"),
                    (72, "72 سال"),
                    (73, "73 سال"),
                    (74, "74 سال"),
                    (75, "75 سال"),
                    (76, "76 سال"),
                    (77, "77 سال"),
                    (78, "78 سال"),
                    (79, "79 سال"),
                    (80, "80 سال"),
                    (81, "81 سال"),
                    (82, "82 سال"),
                    (83, "83 سال"),
                    (84, "84 سال"),
                    (85, "85 سال"),
                    (86, "86 سال"),
                    (87, "87 سال"),
                    (88, "88 سال"),
                    (89, "89 سال"),
                    (90, "90 سال"),
                    (91, "91 سال"),
                    (92, "92 سال"),
                    (93, "93 سال"),
                    (94, "94 سال"),
                    (95, "95 سال"),
                    (96, "96 سال"),
                    (97, "97 سال"),
                    (98, "98 سال"),
                    (99, "99 سال"),
                ],
                null=True,
                verbose_name="سن",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="beauty",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
                verbose_name="میزان زیبایی (از ۱ تا ۵)",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="درباره من"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="car_status",
            field=models.CharField(
                blank=True,
                choices=[("ندارم", "ندارم"), ("داخلی", "داخلی"), ("خارجی", "خارجی")],
                max_length=100,
                null=True,
                verbose_name="وضعیت خودرو",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="children_count",
            field=models.IntegerField(default=0, verbose_name="تعداد فرزندان"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="شهر"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(max_length=150, verbose_name="نام نمایشی"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="eldest_child_age",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="سن بزرگترین فرزند"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("مرد", "مرد"), ("زن", "زن")],
                max_length=10,
                null=True,
                verbose_name="جنسیت",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="health_status",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="وضعیت سلامتی"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.FloatField(
                blank=True, null=True, verbose_name="قد (سانتی\u200cمتر)"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="housing_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ندارم", "ندارم"),
                    ("اجاره\u200cای", "اجاره\u200cای"),
                    ("شخصی", "شخصی"),
                ],
                max_length=100,
                null=True,
                verbose_name="وضعیت مسکن",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="income",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ندارم", "ندارم"),
                    ("کمتر از ۱۰ میلیون تومان", "کمتر از ۱۰ میلیون تومان"),
                    ("بین ۱۰ تا ۲۰ میلیون تومان", "بین ۱۰ تا ۲۰ میلیون تومان"),
                    ("بین ۲۰ تا ۵۰ میلیون تومان", "بین ۲۰ تا ۵۰ میلیون تومان"),
                    ("بیشتر از ۵۰ میلیون تومان", "بیشتر از ۵۰ میلیون تومان"),
                ],
                max_length=100,
                null=True,
                verbose_name="درآمد ماهانه",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_totp_enabled",
            field=models.BooleanField(
                default=False, verbose_name="تایید دو مرحله\u200cای فعال است؟"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="lifestyle",
            field=models.CharField(
                blank=True,
                choices=[("با خانواده", "با خانواده"), ("مستقل", "مستقل")],
                max_length=20,
                null=True,
                verbose_name="سبک زندگی",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("مجرد", "مجرد"),
                    ("متاهل", "متاهل"),
                    ("مطلقه", "مطلقه"),
                    ("همسر فوت شده", "همسر فوت شده"),
                ],
                max_length=20,
                null=True,
                verbose_name="وضعیت تاهل",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                max_length=15, unique=True, verbose_name="شماره موبایل"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.user_directory_path,
                verbose_name="عکس پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="استان"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="کد معرف",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="معرف",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="security_phrase",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="عبارت امنیتی"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="seeking",
            field=models.CharField(
                blank=True,
                choices=[
                    ("دوست", "دوست"),
                    ("دوستی با مزایا", "دوستی با مزایا"),
                    ("رابطه بدون تعهد", "رابطه بدون تعهد"),
                    ("پارتنر", "پارتنر"),
                    ("هم\u200cاتاقی", "هم\u200cاتاقی"),
                    ("همسر", "همسر"),
                ],
                max_length=20,
                null=True,
                verbose_name="دنبال چه هستید؟",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="show_location",
            field=models.BooleanField(default=False, verbose_name="نمایش موقعیت مکانی"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="skin_color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("سفید", "سفید"),
                    ("گندمی", "گندمی"),
                    ("سبزه روشن", "سبزه روشن"),
                    ("سبزه تیره", "سبزه تیره"),
                    ("سیاه", "سیاه"),
                ],
                max_length=50,
                null=True,
                verbose_name="رنگ پوست",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="spouse_expectation",
            field=models.TextField(
                blank=True, null=True, verbose_name="انتظارات از همسر/دوست"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("فعال", "فعال"),
                    ("مسدود", "مسدود"),
                    ("تایید نشده", "تایید نشده"),
                ],
                default="تایید نشده",
                max_length=20,
                verbose_name="وضعیت حساب",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("محجبه", "محجبه"),
                    ("بدون حجاب", "بدون حجاب"),
                    ("سایر", "سایر"),
                ],
                max_length=20,
                null=True,
                verbose_name="سبک پوشش",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="target_gender",
            field=models.CharField(
                blank=True,
                choices=[("مرد", "مرد"), ("زن", "زن")],
                max_length=10,
                null=True,
                verbose_name="جنسیت مورد نظر",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.FloatField(
                blank=True, null=True, verbose_name="وزن (کیلوگرم)"
            ),
        ),
    ]
