# Generated by Django 5.0.14 on 2026-06-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_birth_date_customuser_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bot_verification_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_bot_verified",
            field=models.BooleanField(
                default=False, verbose_name="تایید شده توسط ربات"
            ),
        ),
    ]
