# Generated by Django 5.0.14 on 2026-06-09 07:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_bot_verification_token_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="target_gender",
        ),
        migrations.AddField(
            model_name="customuser",
            name="interested_in",
            field=models.JSONField(blank=True, null=True, verbose_name="جنسیت‌های مورد علاقه"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("مرد", "مرد"), ("زن", "زن"), ("ترنس", "ترنس")],
                max_length=10,
                null=True,
                verbose_name="جنسیت",
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(fields=["gender"], name="accounts_cu_gender_528788_idx"),
        ),
    ]
