# Generated by Django 5.0.14 on 2026-06-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_spin_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخرین چرخش گردونه"
            ),
        ),
    ]
