# Generated by Django 5.0.14 on 2026-06-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_customuser_last_spin_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="consecutive_losses",
            field=models.IntegerField(default=0, verbose_name="باخت\u200cهای متوالی"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="آخرین فعالیت"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="lifetime_coin_burn",
            field=models.IntegerField(
                default=0, verbose_name="کل سکه\u200cهای مصرف شده"
            ),
        ),
    ]
