# Generated by Django 5.0.14 on 2026-06-10 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_consecutive_losses_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhaleUser",
            fields=[],
            options={
                "verbose_name": "کاربر ویژه (Whale)",
                "verbose_name_plural": "کاربران ویژه (Whales)",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.customuser",),
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="referred_by",
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_commission_earned",
            field=models.IntegerField(default=0, verbose_name="کل کمیسیون دریافتی"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="total_spent_coins",
            field=models.IntegerField(
                default=0, verbose_name="کل سکه\u200cهای مصرف شده (ضد تقلب)"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="unclaimed_commission",
            field=models.IntegerField(default=0, verbose_name="کمیسیون دریافت نشده"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(
                blank=True, max_length=6, null=True, unique=True, verbose_name="کد معرف"
            ),
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_generated",
                    models.IntegerField(default=0, verbose_name="کمیسیون تولید شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "referred_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_info",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر دعوت شده",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="made_referrals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="معرف",
                    ),
                ),
            ],
            options={
                "verbose_name": "معرفی",
                "verbose_name_plural": "معرفی\u200cها",
            },
        ),
    ]
