# Generated by Django 5.0.14 on 2026-05-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftpacket",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="subscriptions/icons/"
            ),
        ),
    ]
