# Generated by Django 5.0.14 on 2026-05-29 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_giftpacket_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("coins", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name="cointransaction",
            name="after_balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cointransaction",
            name="before_balance",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscriptions.plan",
            ),
        ),
    ]
