# Generated by Django 5.0.14 on 2026-05-28 18:50

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TruthDareQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "q_type",
                    models.CharField(
                        choices=[("TRUTH", "Truth"), ("DARE", "Dare")], max_length=10
                    ),
                ),
                ("text", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("TRUTH_DARE", "Truth or Dare"),
                            ("HOKM", "Hokm"),
                            ("MANCHE", "Manche"),
                            ("SNAKES", "Snakes & Ladders"),
                            ("AMIRZA", "Amirza"),
                        ],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(default="WAITING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("entry_fee", models.IntegerField(default=10)),
                ("reward_pool", models.IntegerField(default=0)),
                (
                    "players",
                    models.ManyToManyField(
                        related_name="game_rooms", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
