# Generated by Django 5.0.14 on 2026-06-10 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price_coins", models.IntegerField(default=10)),
                (
                    "animation_url",
                    models.CharField(
                        blank=True,
                        help_text="URL/Path to animation asset",
                        max_length=200,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LootBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "price_coins",
                    models.IntegerField(default=0, help_text="0 means free/daily"),
                ),
                ("is_premium", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="gameroom",
            name="capacity",
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name="gameroom",
            name="fast_track_fee",
            field=models.IntegerField(default=0, help_text="Fee to skip the queue"),
        ),
        migrations.AddField(
            model_name="gameroom",
            name="state",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="gameroom",
            name="status",
            field=models.CharField(
                choices=[
                    ("WAITING", "Waiting"),
                    ("STARTING", "Starting"),
                    ("IN_PROGRESS", "In Progress"),
                    ("FINISHED", "Finished"),
                ],
                default="WAITING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BetHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "target",
                    models.CharField(help_text="Who/What they bet on", max_length=100),
                ),
                ("won", models.BooleanField(default=False)),
                ("payout", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bets",
                        to="games.gameroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LootBoxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "weight",
                    models.IntegerField(
                        default=10, help_text="Higher weight = higher chance"
                    ),
                ),
                ("payout_coins", models.IntegerField(default=0)),
                ("is_jackpot", models.BooleanField(default=False)),
                (
                    "loot_box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="games.lootbox",
                    ),
                ),
            ],
        ),
    ]
