# Generated by Django 5.0.14 on 2026-06-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_gift_lootbox_gameroom_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameroom",
            name="commission_processed",
            field=models.BooleanField(default=False),
        ),
    ]
