# Generated by Django 5.0.14 on 2026-05-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "New Message"),
                    ("subscription_approved", "Subscription Approved"),
                    ("coin_earned", "Coin Earned"),
                    ("gift_received", "Gift Received"),
                    ("call_incoming", "Incoming Call"),
                    ("lottery_won", "Lottery Won"),
                    ("profile_visited", "Profile Visited"),
                    ("system", "System"),
                ],
                default="system",
                max_length=50,
            ),
        ),
    ]
